# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys


from selenium.webdriver.support import expected_conditions as EC


class TestTransaction():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    #self.driver=webdriver.Edge()

    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1280, 672)
    self.driver.find_element(By.ID, "username").send_keys("Heath93")
    self.driver.find_element(By.ID, "password").send_keys("s3cret")
    self.driver.find_element(By.CSS_SELECTOR, "[data-test=\"signin-submit\"]").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"nav-top-new-transaction\"]").click()
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"nav-top-new-transaction\"]")
    time.sleep(3)
    # Wait for the navigation to complete
    WebDriverWait(self.driver, 10).until(
        EC.url_to_be("http://localhost:3000/transaction/new")
    )

    # Wait for the navigation to complete
   

    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_transcationSearchInputMatching(self):
   
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root > .MuiSvgIcon-root").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"user-list-search-input\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"user-list-search-input\"]").send_keys("abeer")
    time.sleep(3)
    self.vars["abeer"] = self.driver.find_element(By.CSS_SELECTOR, ".css-1p823my-MuiListItem-root:nth-child(1) .MuiTypography-body1").text
  
  def test_transcationSearchInputDonNotMatching(self):
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root > .MuiSvgIcon-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-root > .MuiSvgIcon-root").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"user-list-search-input\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"user-list-search-input\"]").send_keys("naden")
    time.sleep(3)
    assert self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"user-list-item-uBmeaz5pX\"]").text == "user not found"
  
  def test_transcationRequestProcess(self):
   
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"nav-top-new-transaction\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiListItem-root:nth-child(1) .MuiGrid-root > .MuiGrid-root:nth-child(1)").click()
    self.driver.find_element(By.ID, "amount").send_keys("$100")
    self.driver.find_element(By.ID, "transaction-create-description-input").send_keys("Sam\'s gift")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"transaction-create-submit-request\"]").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".MuiGrid-root:nth-child(1) > .css-mpyo7s-MuiTypography-root").text == "Requested $100.00 for Sam's gift"
  
  def test_transcationPaymentProcess(self):
   
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"nav-top-new-transaction\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-1p823my-MuiListItem-root:nth-child(2) .MuiTypography-body1").click()
    self.driver.find_element(By.ID, "amount").click()
    self.driver.find_element(By.ID, "amount").send_keys("$50")
    self.driver.find_element(By.ID, "transaction-create-description-input").click()
    self.driver.find_element(By.ID, "transaction-create-description-input").send_keys("Thank You :)")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"transaction-create-submit-payment\"]").click()
    self.vars["Paid $50.00 for Thank You :)"] = self.driver.find_element(By.CSS_SELECTOR, ".MuiGrid-root:nth-child(1) > .css-mpyo7s-MuiTypography-root").text
  
